//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mooho.Base.Common;
using Mooho.Base.Model;
using accreditation.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;

namespace accreditation.IDataAccess
{
    /// <summary>
    /// 课程数据访问接口
    /// </summary>
    public partial interface ICourseDataAccess
    {
        /// <summary>
        /// 新增课程
        /// </summary>
        /// <param name="course">课程</param>
        /// <return>课程</return>
        Course AddCourse(Course course);

        /// <summary>
        /// 修改课程
        /// </summary>
        /// <param name="course">课程</param>
        /// <return>课程</return>
        Course UpdateCourse(Course course);

        /// <summary>
        /// 保存课程
        /// </summary>
        /// <param name="course">课程</param>
        /// <return>课程</return>
        Course SaveCourse(Course course);

        /// <summary>
        /// 删除课程
        /// </summary>
        /// <param name="course">课程</param>
        void RemoveCourse(Course course);

        /// <summary>
        /// 根据条件删除课程
        /// </summary>
        /// <param name="predicate">查询条件</param>
        void RemoveCourse(Expression<Func<Course, bool>> predicate);

        /// <summary>
        /// 获取课程
        /// </summary>
        /// <param name="id">唯一编号</param>
        /// <returns>课程</returns>
        Course GetCourse(long id);

        /// <summary>
        /// 获取课程
        /// </summary>
        /// <param name="id">唯一编号</param>
        /// <param name="defaultEntity">默认值</param>
        /// <returns>课程</returns>
        Course GetCourseOrDefault(long id, Course defaultEntity = null);

        /// <summary>
        /// 根据条件获取课程
        /// </summary>
        /// <param name="predicate">查询条件</param>
        /// <returns>课程</returns>
        Course GetCourse(Expression<Func<Course, bool>> predicate);

        /// <summary>
        /// 根据条件获取课程
        /// </summary>
        /// <param name="predicate">查询条件</param>
        /// <param name="defaultEntity">默认值</param>
        /// <returns>课程</returns>
        Course GetCourseOrDefault(Expression<Func<Course, bool>> predicate, Course defaultEntity = null);

        /// <summary>
        /// 根据条件获取课程数量
        /// </summary>
        /// <param name="predicate">查询条件</param>
        /// <returns>课程数量</returns>
        int CountCourse(Expression<Func<Course, bool>> predicate);

        /// <summary>
        /// 根据条件统计课程
        /// </summary>
        /// <param name="selecter">统计字段</param>
        /// <param name="predicate">查询条件</param>
        /// <returns>统计值</returns>
        int? SumCourse(Expression<Func<Course, int?>> selecter, Expression<Func<Course, bool>> predicate);

        /// <summary>
        /// 根据条件统计课程
        /// </summary>
        /// <param name="selecter">统计字段</param>
        /// <param name="predicate">查询条件</param>
        /// <returns>统计值</returns>
        decimal? SumCourse(Expression<Func<Course, decimal?>> selecter, Expression<Func<Course, bool>> predicate);

        /// <summary>
        /// 根据条件查询课程
        /// </summary>
        /// <param name="predicate">查询条件</param>
        /// <param name="pages">分页信息</param>
        /// <returns>课程集合</returns>
        List<Course> QueryCourse(Expression<Func<Course, bool>> predicate, Pages pages = null);

        /// <summary>
        /// 根据条件查询课程
        /// </summary>
        /// <param name="predicate">查询条件</param>
        /// <param name="dynamicPredicate">动态查询条件</param>
        /// <param name="pages">分页信息</param>
        /// <returns>课程集合</returns>
        List<Course> QueryCourse(Expression<Func<Course, bool>> predicate, LambdaExpression dynamicPredicate, Pages pages = null);
    }
}
