
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using accreditation.DataAccess;
using accreditation.Model;
using Mooho.Base.Common;
using System;
using System.Linq;

namespace accreditation.DataAccess
{
    public partial class Entities
    {
		/// <summary>
        /// 获取或设置考核分解项
        /// </summary>
        public virtual DbSet<AssessFragment> AssessFragments { get; set; }

		/// <summary>
        /// 获取或设置考核方式
        /// </summary>
        public virtual DbSet<AssessMethod> AssessMethods { get; set; }

		/// <summary>
        /// 获取或设置课程
        /// </summary>
        public virtual DbSet<Course> Courses { get; set; }

		/// <summary>
        /// 获取或设置课程目标
        /// </summary>
        public virtual DbSet<CourseTarget> CourseTargets { get; set; }

		/// <summary>
        /// 获取或设置培养计划
        /// </summary>
        public virtual DbSet<CultivationProject> CultivationProjects { get; set; }

		/// <summary>
        /// 获取或设置毕业指标点
        /// </summary>
        public virtual DbSet<GraduationPoint> GraduationPoints { get; set; }

		/// <summary>
        /// 获取或设置毕业要求
        /// </summary>
        public virtual DbSet<GraduationReq> GraduationReqs { get; set; }

		/// <summary>
        /// 获取或设置学生信息
        /// </summary>
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }

		/// <summary>
        /// 获取或设置教学大纲
        /// </summary>
        public virtual DbSet<Syllabuse> Syllabuses { get; set; }

		/// <summary>
        /// 获取或设置教师信息
        /// </summary>
        public virtual DbSet<TeacherInfo> TeacherInfoes { get; set; }

		/// <summary>
        /// 获取或设置教学班
        /// </summary>
        public virtual DbSet<TeachingTeachclasse> TeachingTeachclasses { get; set; }

        /// <summary>
        /// 模型创建
        /// </summary>
        /// <param name="modelBuilder">模型生成器</param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }
}
