//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mooho.Base.Common;
using Mooho.Base.Model;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.Serialization;

namespace accreditation.Model
{
    /// <summary>
    /// 课程
    /// </summary>
	[Description("课程")]
    [Table("acc_course")]
    public partial class Course : EntityBase
    {
        /// <summary>
        /// 获取或设置课程id编号
        /// </summary>
		[Description("课程id编号")]
        [Key]
        [DataMember]
        [Column("id")]
        public long ID { get; set; }

        /// <summary>
        /// 获取或设置大纲id编号
        /// </summary>
		[Description("大纲id编号")]
        [DataMember]
        [Column("syllabus_id")]
        public long? SyllabusID { get; set; }

        /// <summary>
        /// 获取或设置课程名称
        /// </summary>
		[Description("课程名称")]
        [DataMember]
        [Column("course_name")]
        public string CourseName { get; set; }

        /// <summary>
        /// 获取或设置课程类型
        /// </summary>
		[Description("课程类型")]
        [DataMember]
        [Column("type")]
        public string Type { get; set; }

        /// <summary>
        /// 获取或设置内容
        /// </summary>
		[Description("内容")]
        [DataMember]
        [Column("content")]
        public string Content { get; set; }

        /// <summary>
        /// 获取或设置创建者编号
        /// </summary>
		[Description("创建者编号")]
        [DataMember]
        [Column("create_user_id")]
        public long? CreateUserID { get; set; }

        /// <summary>
        /// 获取或设置创建时间
        /// </summary>
		[Description("创建时间")]
        [DataMember]
        [Column("create_time", TypeName="datetime")]
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// 获取或设置最后更新人编号
        /// </summary>
		[Description("最后更新人编号")]
        [DataMember]
        [Column("update_user_id")]
        public long? UpdateUserID { get; set; }

        /// <summary>
        /// 获取或设置最后更新时间
        /// </summary>
		[Description("最后更新时间")]
        [DataMember]
        [Column("update_time", TypeName="datetime")]
        public DateTime? UpdateTime { get; set; }

        /// <summary>
        /// 获取或设置大纲id
        /// </summary>
        [DataMember]
		[Description("大纲id")]
        [ForeignKey("SyllabusID")]
        public virtual Syllabuse Syllabus { get; set; }

    }
}
