//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mooho.Base.Common;
using Mooho.Base.Model;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.Serialization;

namespace accreditation.Model
{
    /// <summary>
    /// 培养计划
    /// </summary>
	[Description("培养计划")]
    [Table("acc_cultivation_project")]
    public partial class CultivationProject : EntityBase
    {
        /// <summary>
        /// 获取或设置培养方案ID编号
        /// </summary>
		[Description("培养方案ID编号")]
        [Key]
        [DataMember]
        [Column("id")]
        public long ID { get; set; }

        /// <summary>
        /// 获取或设置培养方案代码
        /// </summary>
		[Description("培养方案代码")]
        [DataMember]
        [Column("cultivation_code")]
        public string CultivationCode { get; set; }

        /// <summary>
        /// 获取或设置培养方案类型
        /// </summary>
		[Description("培养方案类型")]
        [DataMember]
        [Column("cultivation_type")]
        public string CultivationType { get; set; }

        /// <summary>
        /// 获取或设置培养方案内容
        /// </summary>
		[Description("培养方案内容")]
        [DataMember]
        [Column("content")]
        public string Content { get; set; }

        /// <summary>
        /// 获取或设置创建人编号
        /// </summary>
		[Description("创建人编号")]
        [DataMember]
        [Column("create_user_id")]
        public long? CreateUserID { get; set; }

        /// <summary>
        /// 获取或设置创建时间
        /// </summary>
		[Description("创建时间")]
        [DataMember]
        [Column("create_time", TypeName="datetime")]
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// 获取或设置最后更新人编号
        /// </summary>
		[Description("最后更新人编号")]
        [DataMember]
        [Column("update_user_id")]
        public long? UpdateUserID { get; set; }

        /// <summary>
        /// 获取或设置最后更新时间
        /// </summary>
		[Description("最后更新时间")]
        [DataMember]
        [Column("update_time", TypeName="datetime")]
        public DateTime? UpdateTime { get; set; }

    }
}
