//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mooho.Base.Common;
using Mooho.Base.Model;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.Serialization;

namespace accreditation.Model
{
    /// <summary>
    /// 学生信息
    /// </summary>
	[Description("学生信息")]
    [Table("acc_student_info")]
    public partial class StudentInfo : EntityBase
    {
        /// <summary>
        /// 获取或设置学生ID编号
        /// </summary>
		[Description("学生ID编号")]
        [Key]
        [DataMember]
        [Column("id")]
        public long ID { get; set; }

        /// <summary>
        /// 获取或设置学生姓名
        /// </summary>
		[Description("学生姓名")]
        [DataMember]
        [Column("name")]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置学生学号
        /// </summary>
		[Description("学生学号")]
        [DataMember]
        [Column("student_number")]
        public string StudentNumber { get; set; }

        /// <summary>
        /// 获取或设置班级
        /// </summary>
		[Description("班级")]
        [DataMember]
        [Column("grade_class")]
        public string GradeClass { get; set; }

        /// <summary>
        /// 获取或设置创建人ID编号
        /// </summary>
		[Description("创建人ID编号")]
        [DataMember]
        [Column("create_user_id")]
        public long? CreateUserID { get; set; }

        /// <summary>
        /// 获取或设置创建时间
        /// </summary>
		[Description("创建时间")]
        [DataMember]
        [Column("create_time", TypeName="datetime")]
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// 获取或设置最后更新人编号
        /// </summary>
		[Description("最后更新人编号")]
        [DataMember]
        [Column("update_user_id")]
        public long? UpdateUserID { get; set; }

        /// <summary>
        /// 获取或设置最后更新时间
        /// </summary>
		[Description("最后更新时间")]
        [DataMember]
        [Column("update_time", TypeName="datetime")]
        public DateTime? UpdateTime { get; set; }

    }
}
