//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mooho.Base.Common;
using Mooho.Base.Model;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.Serialization;

namespace accreditation.Model
{
    /// <summary>
    /// 教学大纲
    /// </summary>
	[Description("教学大纲")]
    [Table("acc_syllabuse")]
    public partial class Syllabuse : EntityBase
    {
        /// <summary>
        /// 获取或设置大纲ID编号
        /// </summary>
		[Description("大纲ID编号")]
        [Key]
        [DataMember]
        [Column("id")]
        public long ID { get; set; }

        /// <summary>
        /// 获取或设置教材
        /// </summary>
		[Description("教材")]
        [DataMember]
        [Column("syll_material")]
        public string SyllMaterial { get; set; }

        /// <summary>
        /// 获取或设置大纲属性
        /// </summary>
		[Description("大纲属性")]
        [DataMember]
        [Column("syll_properties")]
        public string SyllProperties { get; set; }

        /// <summary>
        /// 获取或设置课时
        /// </summary>
		[Description("课时")]
        [DataMember]
        [Column("credit_hours")]
        public long? CreditHours { get; set; }

        /// <summary>
        /// 获取或设置学分
        /// </summary>
		[Description("学分")]
        [DataMember]
        [Column("credit_number")]
        public long? CreditNumber { get; set; }

        /// <summary>
        /// 获取或设置课程专业
        /// </summary>
		[Description("课程专业")]
        [DataMember]
        [Column("tech_major")]
        public string TechMajor { get; set; }

        /// <summary>
        /// 获取或设置内容
        /// </summary>
		[Description("内容")]
        [DataMember]
        [Column("content")]
        public string Content { get; set; }

        /// <summary>
        /// 获取或设置创建者编号
        /// </summary>
		[Description("创建者编号")]
        [DataMember]
        [Column("create_user_id")]
        public long? CreateUserID { get; set; }

        /// <summary>
        /// 获取或设置创建时间
        /// </summary>
		[Description("创建时间")]
        [DataMember]
        [Column("create_time", TypeName="datetime")]
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// 获取或设置最后创建者编号
        /// </summary>
		[Description("最后创建者编号")]
        [DataMember]
        [Column("update_user_id")]
        public long? UpdateUserID { get; set; }

        /// <summary>
        /// 获取或设置最后创建时间
        /// </summary>
		[Description("最后创建时间")]
        [DataMember]
        [Column("update_time", TypeName="datetime")]
        public DateTime? UpdateTime { get; set; }

        /// <summary>
        /// 获取或设置课程
        /// </summary>
        [InverseProperty("Syllabus")]
        public virtual ICollection<Course> CourseEntitiesOfSyllabus { get; set; }

        /// <summary>
        /// 获取或设置课程
        /// </summary>
        [NotMapped]
        private ICollection<Course> CourseInternalEntitiesOfSyllabus { get; set; }

        /// <summary>
        /// 获取或设置课程
        /// </summary>
        [NotMapped]
        public ICollection<Course> CoursesOfSyllabus
        {
            get
            {
                if (this.CourseInternalEntitiesOfSyllabus == null)
                {
                    this.CourseInternalEntitiesOfSyllabus = this.CourseEntitiesOfSyllabus == null ? new List<Course>() : this.CourseEntitiesOfSyllabus.ToList();
                }

                return this.CourseInternalEntitiesOfSyllabus;
            }
            set
            {
                this.CourseEntitiesOfSyllabus = value;
                this.CourseInternalEntitiesOfSyllabus = value;
            }
        }

    }
}
